In [1]:
import pandas as pd

In [4]:
data = pd.read_csv('/content/Lending-company.csv', index_col = 'StringID')

In [5]:
lending_co_data = data.copy()
lending_co_data.head()

,LoanID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
StringID,,,,,,,,,,,,,,
LoanID_1,1,Product B,Female,Location 3,Region 2,17600.0,04/07/2018,2200,45,365,3221,4166,14621,Active
LoanID_2,2,Product D,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
LoanID_3,3,Product B,Male,Location 8,Region 3,16600.0,08/12/2016,1000,45,365,2260,3205,16340,NaN
LoanID_4,4,Product A,Male,Location 26,Region 2,17600.0,NaN,2200,45,365,3141,4166,16321,Active
LoanID_5,5,Product B,Female,Location 34,Region 3,21250.0,28/10/2017,2200,55,365,3570,4745,14720,Active

In [6]:
lending_co_data.describe(include='all')

,LoanID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
count,1043.000000,1043,1043,1043,1042,1018.000000,1042,1043.000000,1043.000000,1043.0,1043.000000,1043.000000,1043.000000,1006
unique,NaN,6,3,296,18,NaN,742,NaN,NaN,NaN,NaN,NaN,NaN,3
top,NaN,Product B,Male,Location 25,Region 6,NaN,23/04/2019,NaN,NaN,NaN,NaN,NaN,NaN,Finished Payment
freq,NaN,400,624,31,326,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,534
mean,522.000000,NaN,NaN,NaN,NaN,19562.843811,NaN,2528.092042,50.834132,365.0,3901.857143,5214.393097,17122.131352,NaN
std,301.232468,NaN,NaN,NaN,NaN,5955.588065,NaN,1504.467724,11.567390,0.0,2537.597667,2850.327133,5910.916736,NaN
min,1.000000,NaN,NaN,NaN,NaN,13475.000000,NaN,1000.000000,30.000000,365.0,-2770.000000,-2945.000000,650.000000,NaN
25%,261.500000,NaN,NaN,NaN,NaN,16300.000000,NaN,2200.000000,45.000000,365.0,2840.500000,3822.000000,15560.500000,NaN
50%,522.000000,NaN,NaN,NaN,NaN,17600.000000,NaN,2200.000000,45.000000,365.0,3420.000000,4742.000000,16617.000000,NaN
75%,782.500000,NaN,NaN,NaN,NaN,20950.000000,NaN,2200.000000,55.000000,365.0,5075.500000,6393.000000,19977.500000,NaN
max,1043.000000,NaN,NaN,NaN,NaN,70225.000000,NaN,8000.000000,150.000000,365.0,18851.000000,22143.000000,65001.000000,NaN

In [9]:
lending_co_data['Product'].head(10)

StringID
LoanID_1     Product B
LoanID_2     Product D
LoanID_3     Product B
LoanID_4     Product A
LoanID_5     Product B
LoanID_6     Product A
LoanID_7     Product A
LoanID_8     Product D
LoanID_9     Product A
LoanID_10    Product C
Name: Product, dtype: object

In [10]:
lending_co_data.head(2)

,LoanID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
StringID,,,,,,,,,,,,,,
LoanID_1,1,Product B,Female,Location 3,Region 2,17600.0,04/07/2018,2200,45,365,3221,4166,14621,Active
LoanID_2,2,Product D,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active

In [8]:
lending_co_data.iloc[1]

LoanID                     2
Product            Product D
CustomerGender        Female
Location          Location 6
Region              Region 6
TotalPrice               NaN
StartDate         02/01/2019
Deposit                 2200
DailyRate                 45
TotalDaysYr              365
AmtPaid36               3161
AmtPaid60               4096
AmtPaid360             16041
LoanStatus            Active
Name: LoanID_2, dtype: object

In [12]:
lending_co_data.iloc[1, 3]

'Location 6'

In [14]:
lending_co_data.iloc[1, : ]

LoanID                     2
Product            Product D
CustomerGender        Female
Location          Location 6
Region              Region 6
TotalPrice               NaN
StartDate         02/01/2019
Deposit                 2200
DailyRate                 45
TotalDaysYr              365
AmtPaid36               3161
AmtPaid60               4096
AmtPaid360             16041
LoanStatus            Active
Name: LoanID_2, dtype: object

In [17]:
lending_co_data.iloc[:, 3]

StringID
LoanID_1        Location 3
LoanID_2        Location 6
LoanID_3        Location 8
LoanID_4       Location 26
LoanID_5       Location 34
                  ...
LoanID_1039    Location 73
LoanID_1040    Location 82
LoanID_1041    Location 11
LoanID_1042    Location 26
LoanID_1043    Location 94
Name: Location, Length: 1043, dtype: object

In [18]:
type(lending_co_data.iloc[1, 3])

str

In [19]:
type(lending_co_data.iloc[1, :])

pandas.core.series.Series

In [21]:
type(lending_co_data.iloc[:, 3])

pandas.core.series.Series

In [22]:
lending_co_data.iloc[[1,3], :]

,LoanID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
StringID,,,,,,,,,,,,,,
LoanID_2,2,Product D,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
LoanID_4,4,Product A,Male,Location 26,Region 2,17600.0,NaN,2200,45,365,3141,4166,16321,Active

In [23]:
lending_co_data.iloc[1:3, :]

,LoanID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
StringID,,,,,,,,,,,,,,
LoanID_2,2,Product D,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
LoanID_3,3,Product B,Male,Location 8,Region 3,16600.0,08/12/2016,1000,45,365,2260,3205,16340,NaN

In [34]:
lending_co_data.iloc[1:8, :]

,LoanID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
StringID,,,,,,,,,,,,,,
LoanID_2,2,Product D,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
LoanID_3,3,Product B,Male,Location 8,Region 3,16600.0,08/12/2016,1000,45,365,2260,3205,16340,NaN
LoanID_4,4,Product A,Male,Location 26,Region 2,17600.0,NaN,2200,45,365,3141,4166,16321,Active
LoanID_5,5,Product B,Female,Location 34,Region 3,21250.0,28/10/2017,2200,55,365,3570,4745,14720,Active
LoanID_6,6,Product A,Male,Location 34,Region 1,NaN,19/04/2019,2200,45,365,3301,4066,15141,Active
LoanID_7,7,Product A,Male,Location 25,NaN,21250.0,04/07/2020,2200,55,365,1951,3176,18701,Active
LoanID_8,8,Product D,Male,Location 46,Region 5,17600.0,24/04/2018,2200,45,365,4071,4056,16351,Active

In [33]:
lending_co_data.iloc[:, [3,1]].head()

             Location    Product
StringID
LoanID_1   Location 3  Product B
LoanID_2   Location 6  Product D
LoanID_3   Location 8  Product B
LoanID_4  Location 26  Product A
LoanID_5  Location 34  Product B

In [32]:
lending_co_data.iloc[:, [3, 1, -1]].head(7)

             Location    Product LoanStatus
StringID
LoanID_1   Location 3  Product B     Active
LoanID_2   Location 6  Product D     Active
LoanID_3   Location 8  Product B        NaN
LoanID_4  Location 26  Product A     Active
LoanID_5  Location 34  Product B     Active
LoanID_6  Location 34  Product A     Active
LoanID_7  Location 25  Product A     Active

In [37]:
lending_co_data.head(3)

,LoanID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
StringID,,,,,,,,,,,,,,
LoanID_1,1,Product B,Female,Location 3,Region 2,17600.0,04/07/2018,2200,45,365,3221,4166,14621,Active
LoanID_2,2,Product D,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
LoanID_3,3,Product B,Male,Location 8,Region 3,16600.0,08/12/2016,1000,45,365,2260,3205,16340,NaN

In [35]:
lending_co_data.loc['LoanID_3']

LoanID                     3
Product            Product B
CustomerGender          Male
Location          Location 8
Region              Region 3
TotalPrice           16600.0
StartDate         08/12/2016
Deposit                 1000
DailyRate                 45
TotalDaysYr              365
AmtPaid36               2260
AmtPaid60               3205
AmtPaid360             16340
LoanStatus               NaN
Name: LoanID_3, dtype: object

In [38]:
lending_co_data.loc['LoanID_3', :]

LoanID                     3
Product            Product B
CustomerGender          Male
Location          Location 8
Region              Region 3
TotalPrice           16600.0
StartDate         08/12/2016
Deposit                 1000
DailyRate                 45
TotalDaysYr              365
AmtPaid36               2260
AmtPaid60               3205
AmtPaid360             16340
LoanStatus               NaN
Name: LoanID_3, dtype: object

In [40]:
lending_co_data.loc['LoanID_3', 'Region']

'Region 3'

In [42]:
lending_co_data.head(3)

,LoanID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
StringID,,,,,,,,,,,,,,
LoanID_1,1,Product B,Female,Location 3,Region 2,17600.0,04/07/2018,2200,45,365,3221,4166,14621,Active
LoanID_2,2,Product D,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
LoanID_3,3,Product B,Male,Location 8,Region 3,16600.0,08/12/2016,1000,45,365,2260,3205,16340,NaN

In [41]:
lending_co_data.loc['LoanID_3', 'Region':'StartDate']

Region          Region 3
TotalPrice       16600.0
StartDate     08/12/2016
Name: LoanID_3, dtype: object

In [45]:
lending_co_data['Location']

StringID
LoanID_1        Location 3
LoanID_2        Location 6
LoanID_3        Location 8
LoanID_4       Location 26
LoanID_5       Location 34
                  ...
LoanID_1039    Location 73
LoanID_1040    Location 82
LoanID_1041    Location 11
LoanID_1042    Location 26
LoanID_1043    Location 94
Name: Location, Length: 1043, dtype: object

In [47]:
lending_co_data.loc[:,'Location']

StringID
LoanID_1        Location 3
LoanID_2        Location 6
LoanID_3        Location 8
LoanID_4       Location 26
LoanID_5       Location 34
                  ...
LoanID_1039    Location 73
LoanID_1040    Location 82
LoanID_1041    Location 11
LoanID_1042    Location 26
LoanID_1043    Location 94
Name: Location, Length: 1043, dtype: object

In [48]:
lending_co_data.loc[:,'Location'].head()

StringID
LoanID_1     Location 3
LoanID_2     Location 6
LoanID_3     Location 8
LoanID_4    Location 26
LoanID_5    Location 34
Name: Location, dtype: object

In [49]:
lending_co_data.head(5)

,LoanID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
StringID,,,,,,,,,,,,,,
LoanID_1,1,Product B,Female,Location 3,Region 2,17600.0,04/07/2018,2200,45,365,3221,4166,14621,Active
LoanID_2,2,Product D,Female,Location 6,Region 6,NaN,02/01/2019,2200,45,365,3161,4096,16041,Active
LoanID_3,3,Product B,Male,Location 8,Region 3,16600.0,08/12/2016,1000,45,365,2260,3205,16340,NaN
LoanID_4,4,Product A,Male,Location 26,Region 2,17600.0,NaN,2200,45,365,3141,4166,16321,Active
LoanID_5,5,Product B,Female,Location 34,Region 3,21250.0,28/10/2017,2200,55,365,3570,4745,14720,Active

In [52]:
data = {
    "Name": ["Any While", "Jack Stewart", "Richard Lauderdale", "Sara Johnson"],
    "Age": [50, 53, 35, 43],
    "Working Experience (Yrs.)": [5, 8, 3, 10]
}

df = pd.DataFrame(data)

In [53]:
df

                 Name  Age  Working Experience (Yrs.)
0           Any While   50                          5
1        Jack Stewart   53                          8
2  Richard Lauderdale   35                          3
3        Sara Johnson   43                         10

**To complete the task, create a dictionary called data where the values should be pandas Series. Store the pandas Series in variables named names, age, and working_experience_yrs.**

In [54]:
import pandas as pd


names = pd.Series(["Amy White", "Jack Stewart", "Richard Lauderdale", "Sara Johnson"])
age = pd.Series([50, 53, 35, 43])
working_experience_yrs = pd.Series([5, 8, 3, 10])

data = {
    "Name": names,
    "Age": age,
    "Working Experience (Yrs.)": working_experience_yrs
}

df = pd.DataFrame(data)


print(df)

                 Name  Age  Working Experience (Yrs.)
0           Amy White   50                          5
1        Jack Stewart   53                          8
2  Richard Lauderdale   35                          3
3        Sara Johnson   43                         10

In [58]:
import pandas as pd

names = pd.Series(["Amy White", "Jack Stewart", "Richard Lauderdale", "Sara Johnson"])
age = pd.Series([50, 53, 35, 43])
working_experience_yrs = pd.Series([5, 8, 3, 10])


data = {
    "Name": names,
    "Age": age,
    "Working Experience (Yrs.)": working_experience_yrs
}


df = pd.DataFrame(data)

print(df)

                 Name  Age  Working Experience (Yrs.)
0           Amy White   50                          5
1        Jack Stewart   53                          8
2  Richard Lauderdale   35                          3
3        Sara Johnson   43                         10

In [59]:
data = [
    ["Any While", 50, 5],
    ["Jack Stewart", 53, None],
    ["Richard Lauderdale", 35, 3],
    ["Sara Johnson", 43, 10]
]

df = pd.DataFrame(data)

print(df)

                    0   1     2
0           Any While  50   5.0
1        Jack Stewart  53   NaN
2  Richard Lauderdale  35   3.0
3        Sara Johnson  43  10.0

In [60]:
data = [
    ["Any While", 50, 5],
    ["Jack Stewart", 53, None],
    ["Richard Lauderdale", 35, 3],
    ["Sara Johnson", 43, 10]
]

df = pd.DataFrame(data, columns=['Name', 'Age', 'Working Experience (Yrs.)'])

print(df)

                 Name  Age  Working Experience (Yrs.)
0           Any While   50                        5.0
1        Jack Stewart   53                        NaN
2  Richard Lauderdale   35                        3.0
3        Sara Johnson   43                       10.0

In [61]:
data = {
    "Name":['Amy White', 'Jack Stewart', 'Richard Lauderdale', 'Sara Johnson'],
    "Age":[50, 53, 35, 43],
    "Working Experience (Yrs.)":[5,8,3,10]}
df = pd.DataFrame(data, index=[1,2,3,4])
df

                 Name  Age  Working Experience (Yrs.)
1           Amy White   50                          5
2        Jack Stewart   53                          8
3  Richard Lauderdale   35                          3
4        Sara Johnson   43                         10

In [ ]:
def exponentiation_exp_2(x):
    result = x ** 2

    return result


argument = 4
print(exponentiation_exp_2(argument))